pipeline {
    
    agent any 
    def commit_id
    stages('preparation'){
        steps {
            
           checkout scm
           sh " git rev-parse --short HEAD > .git/commit-id "
           commit-id = readFile(.git/commit-id).trim()
        }
            
        }
    stages('test'){
        steps{
            nodejs(nodeJSInstallationName: 'nodejs') {
                sh ' npm install --only=dev'
                sh ' npm test '
            }
            
        }
    }
    stages(' build') {
        steps{
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
        def app = docker.build("nebiha11/docker-demo-jenkins:${commit_id}", '.').push()
     }
     }
   
    }
        
    }
    
}

